networks:
  proxynet:
    external: true
    name: proxynet

services:
  cockpit:
     container_name: autodeko-backend
     image: cockpithq/cockpit:core-latest
     restart: unless-stopped
     networks:
       - proxynet
     volumes:
       - ./addons:/var/www/html/addons
       - ./storage:/var/www/html/storage
       - ./config:/var/www/html/config
